/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub const IOC_IN: u32 = 1073741824;
pub const IOC_OUT: u32 = 2147483648;
pub const IOC_INOUT: u32 = 3221225472;
pub const IOCSIZE_MASK: u32 = 1073676288;
pub const IOCSIZE_SHIFT: u32 = 16;
pub const __BITS_PER_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const KSU_APP_PROFILE_VER: u32 = 4;
pub const KSU_MAX_PACKAGE_NAME: u32 = 256;
pub const KSU_MAX_GROUPS: u32 = 32;
pub const KSU_SELINUX_DOMAIN: u32 = 64;
pub const FLAG_KSU_NO_NEW_PRIVS: u32 = 1;
pub const CSIGNAL: u32 = 255;
pub const CLONE_VM: u32 = 256;
pub const CLONE_FS: u32 = 512;
pub const CLONE_FILES: u32 = 1024;
pub const CLONE_SIGHAND: u32 = 2048;
pub const CLONE_PIDFD: u32 = 4096;
pub const CLONE_PTRACE: u32 = 8192;
pub const CLONE_VFORK: u32 = 16384;
pub const CLONE_PARENT: u32 = 32768;
pub const CLONE_THREAD: u32 = 65536;
pub const CLONE_NEWNS: u32 = 131072;
pub const CLONE_SYSVSEM: u32 = 262144;
pub const CLONE_SETTLS: u32 = 524288;
pub const CLONE_PARENT_SETTID: u32 = 1048576;
pub const CLONE_CHILD_CLEARTID: u32 = 2097152;
pub const CLONE_DETACHED: u32 = 4194304;
pub const CLONE_UNTRACED: u32 = 8388608;
pub const CLONE_CHILD_SETTID: u32 = 16777216;
pub const CLONE_NEWCGROUP: u32 = 33554432;
pub const CLONE_NEWUTS: u32 = 67108864;
pub const CLONE_NEWIPC: u32 = 134217728;
pub const CLONE_NEWUSER: u32 = 268435456;
pub const CLONE_NEWPID: u32 = 536870912;
pub const CLONE_NEWNET: u32 = 1073741824;
pub const CLONE_IO: u32 = 2147483648;
pub const CLONE_CLEAR_SIGHAND: u64 = 4294967296;
pub const CLONE_INTO_CGROUP: u64 = 8589934592;
pub const CLONE_NEWTIME: u32 = 128;
pub const CLONE_ARGS_SIZE_VER0: u32 = 64;
pub const CLONE_ARGS_SIZE_VER1: u32 = 80;
pub const CLONE_ARGS_SIZE_VER2: u32 = 88;
pub const SCHED_NORMAL: u32 = 0;
pub const SCHED_FIFO: u32 = 1;
pub const SCHED_RR: u32 = 2;
pub const SCHED_BATCH: u32 = 3;
pub const SCHED_IDLE: u32 = 5;
pub const SCHED_DEADLINE: u32 = 6;
pub const SCHED_RESET_ON_FORK: u32 = 1073741824;
pub const SCHED_FLAG_RESET_ON_FORK: u32 = 1;
pub const SCHED_FLAG_RECLAIM: u32 = 2;
pub const SCHED_FLAG_DL_OVERRUN: u32 = 4;
pub const SCHED_FLAG_KEEP_POLICY: u32 = 8;
pub const SCHED_FLAG_KEEP_PARAMS: u32 = 16;
pub const SCHED_FLAG_UTIL_CLAMP_MIN: u32 = 32;
pub const SCHED_FLAG_UTIL_CLAMP_MAX: u32 = 64;
pub const SCHED_FLAG_KEEP_ALL: u32 = 24;
pub const SCHED_FLAG_UTIL_CLAMP: u32 = 96;
pub const SCHED_FLAG_ALL: u32 = 127;
pub const KSU_SULOG_EVENT_VERSION: u32 = 1;
pub const TASK_COMM_LEN: u32 = 16;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __kernel_fd_set"][::std::mem::size_of::<__kernel_fd_set>() - 128usize];
    ["Alignment of __kernel_fd_set"][::std::mem::align_of::<__kernel_fd_set>() - 8usize];
    ["Offset of field: __kernel_fd_set::fds_bits"]
        [::std::mem::offset_of!(__kernel_fd_set, fds_bits) - 0usize];
};
pub type __kernel_sighandler_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_old_dev_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __kernel_fsid_t"][::std::mem::size_of::<__kernel_fsid_t>() - 8usize];
    ["Alignment of __kernel_fsid_t"][::std::mem::align_of::<__kernel_fsid_t>() - 4usize];
    ["Offset of field: __kernel_fsid_t::val"]
        [::std::mem::offset_of!(__kernel_fsid_t, val) - 0usize];
};
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = ::std::os::raw::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct root_profile {
    pub uid: __s32,
    pub gid: __s32,
    pub groups_count: __u32,
    pub groups: [__s32; 32usize],
    pub capabilities: root_profile__bindgen_ty_1,
    pub selinux_domain: [::std::os::raw::c_char; 64usize],
    pub namespaces: __s32,
    pub flags: __u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct root_profile__bindgen_ty_1 {
    pub effective: __u64,
    pub permitted: __u64,
    pub inheritable: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of root_profile__bindgen_ty_1"]
        [::std::mem::size_of::<root_profile__bindgen_ty_1>() - 24usize];
    ["Alignment of root_profile__bindgen_ty_1"]
        [::std::mem::align_of::<root_profile__bindgen_ty_1>() - 8usize];
    ["Offset of field: root_profile__bindgen_ty_1::effective"]
        [::std::mem::offset_of!(root_profile__bindgen_ty_1, effective) - 0usize];
    ["Offset of field: root_profile__bindgen_ty_1::permitted"]
        [::std::mem::offset_of!(root_profile__bindgen_ty_1, permitted) - 8usize];
    ["Offset of field: root_profile__bindgen_ty_1::inheritable"]
        [::std::mem::offset_of!(root_profile__bindgen_ty_1, inheritable) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of root_profile"][::std::mem::size_of::<root_profile>() - 248usize];
    ["Alignment of root_profile"][::std::mem::align_of::<root_profile>() - 8usize];
    ["Offset of field: root_profile::uid"][::std::mem::offset_of!(root_profile, uid) - 0usize];
    ["Offset of field: root_profile::gid"][::std::mem::offset_of!(root_profile, gid) - 4usize];
    ["Offset of field: root_profile::groups_count"]
        [::std::mem::offset_of!(root_profile, groups_count) - 8usize];
    ["Offset of field: root_profile::groups"]
        [::std::mem::offset_of!(root_profile, groups) - 12usize];
    ["Offset of field: root_profile::capabilities"]
        [::std::mem::offset_of!(root_profile, capabilities) - 144usize];
    ["Offset of field: root_profile::selinux_domain"]
        [::std::mem::offset_of!(root_profile, selinux_domain) - 168usize];
    ["Offset of field: root_profile::namespaces"]
        [::std::mem::offset_of!(root_profile, namespaces) - 232usize];
    ["Offset of field: root_profile::flags"]
        [::std::mem::offset_of!(root_profile, flags) - 240usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct non_root_profile {
    pub umount_modules: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of non_root_profile"][::std::mem::size_of::<non_root_profile>() - 1usize];
    ["Alignment of non_root_profile"][::std::mem::align_of::<non_root_profile>() - 1usize];
    ["Offset of field: non_root_profile::umount_modules"]
        [::std::mem::offset_of!(non_root_profile, umount_modules) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct app_profile {
    pub version: __u32,
    pub key: [::std::os::raw::c_char; 256usize],
    pub curr_uid: __s32,
    pub allow_su: bool,
    pub __bindgen_anon_1: app_profile__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union app_profile__bindgen_ty_1 {
    pub rp_config: app_profile__bindgen_ty_1__bindgen_ty_1,
    pub nrp_config: app_profile__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct app_profile__bindgen_ty_1__bindgen_ty_1 {
    pub use_default: bool,
    pub template_name: [::std::os::raw::c_char; 256usize],
    pub profile: root_profile,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of app_profile__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<app_profile__bindgen_ty_1__bindgen_ty_1>() - 512usize];
    ["Alignment of app_profile__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<app_profile__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: app_profile__bindgen_ty_1__bindgen_ty_1::use_default"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1__bindgen_ty_1, use_default) - 0usize];
    ["Offset of field: app_profile__bindgen_ty_1__bindgen_ty_1::template_name"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1__bindgen_ty_1, template_name) - 1usize];
    ["Offset of field: app_profile__bindgen_ty_1__bindgen_ty_1::profile"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1__bindgen_ty_1, profile) - 264usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct app_profile__bindgen_ty_1__bindgen_ty_2 {
    pub use_default: bool,
    pub profile: non_root_profile,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of app_profile__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<app_profile__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Alignment of app_profile__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<app_profile__bindgen_ty_1__bindgen_ty_2>() - 1usize];
    ["Offset of field: app_profile__bindgen_ty_1__bindgen_ty_2::use_default"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1__bindgen_ty_2, use_default) - 0usize];
    ["Offset of field: app_profile__bindgen_ty_1__bindgen_ty_2::profile"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1__bindgen_ty_2, profile) - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of app_profile__bindgen_ty_1"]
        [::std::mem::size_of::<app_profile__bindgen_ty_1>() - 512usize];
    ["Alignment of app_profile__bindgen_ty_1"]
        [::std::mem::align_of::<app_profile__bindgen_ty_1>() - 8usize];
    ["Offset of field: app_profile__bindgen_ty_1::rp_config"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1, rp_config) - 0usize];
    ["Offset of field: app_profile__bindgen_ty_1::nrp_config"]
        [::std::mem::offset_of!(app_profile__bindgen_ty_1, nrp_config) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of app_profile"][::std::mem::size_of::<app_profile>() - 784usize];
    ["Alignment of app_profile"][::std::mem::align_of::<app_profile>() - 8usize];
    ["Offset of field: app_profile::version"]
        [::std::mem::offset_of!(app_profile, version) - 0usize];
    ["Offset of field: app_profile::key"][::std::mem::offset_of!(app_profile, key) - 4usize];
    ["Offset of field: app_profile::curr_uid"]
        [::std::mem::offset_of!(app_profile, curr_uid) - 260usize];
    ["Offset of field: app_profile::allow_su"]
        [::std::mem::offset_of!(app_profile, allow_su) - 264usize];
};
pub const KERNEL_SU_UAPI_VERSION: __u32 = 2;
pub const KSU_INSTALL_MAGIC1: __u32 = 3735928559;
pub const KSU_INSTALL_MAGIC2: __u32 = 3405691582;
pub const CHANGE_MANAGER_UID: __u32 = 10006;
pub const KSU_UMOUNT_GETSIZE: __u8 = 107;
pub const KSU_UMOUNT_GETLIST: __u8 = 108;
pub const GET_SULOG_DUMP_V2: __u32 = 10010;
pub const CHANGE_KSUVER: __u32 = 10011;
pub const CHANGE_SPOOF_UNAME: __u32 = 10012;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_become_daemon_cmd {
    pub token: [__u8; 65usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_become_daemon_cmd"][::std::mem::size_of::<ksu_become_daemon_cmd>() - 65usize];
    ["Alignment of ksu_become_daemon_cmd"]
        [::std::mem::align_of::<ksu_become_daemon_cmd>() - 1usize];
    ["Offset of field: ksu_become_daemon_cmd::token"]
        [::std::mem::offset_of!(ksu_become_daemon_cmd, token) - 0usize];
};
pub const EVENT_POST_FS_DATA: __u32 = 1;
pub const EVENT_BOOT_COMPLETED: __u32 = 2;
pub const EVENT_MODULE_MOUNTED: __u32 = 3;
pub const KSU_GET_INFO_FLAG_LKM: __u32 = 1;
pub const KSU_GET_INFO_FLAG_MANAGER: __u32 = 2;
pub const KSU_GET_INFO_FLAG_LATE_LOAD: __u32 = 4;
pub const KSU_GET_INFO_FLAG_PR_BUILD: __u32 = 8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_info_cmd {
    pub version: __u32,
    pub flags: __u32,
    pub features: __u32,
    pub uapi_version: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_info_cmd"][::std::mem::size_of::<ksu_get_info_cmd>() - 16usize];
    ["Alignment of ksu_get_info_cmd"][::std::mem::align_of::<ksu_get_info_cmd>() - 4usize];
    ["Offset of field: ksu_get_info_cmd::version"]
        [::std::mem::offset_of!(ksu_get_info_cmd, version) - 0usize];
    ["Offset of field: ksu_get_info_cmd::flags"]
        [::std::mem::offset_of!(ksu_get_info_cmd, flags) - 4usize];
    ["Offset of field: ksu_get_info_cmd::features"]
        [::std::mem::offset_of!(ksu_get_info_cmd, features) - 8usize];
    ["Offset of field: ksu_get_info_cmd::uapi_version"]
        [::std::mem::offset_of!(ksu_get_info_cmd, uapi_version) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_info_legacy_cmd {
    pub version: __u32,
    pub flags: __u32,
    pub features: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_info_legacy_cmd"][::std::mem::size_of::<ksu_get_info_legacy_cmd>() - 12usize];
    ["Alignment of ksu_get_info_legacy_cmd"]
        [::std::mem::align_of::<ksu_get_info_legacy_cmd>() - 4usize];
    ["Offset of field: ksu_get_info_legacy_cmd::version"]
        [::std::mem::offset_of!(ksu_get_info_legacy_cmd, version) - 0usize];
    ["Offset of field: ksu_get_info_legacy_cmd::flags"]
        [::std::mem::offset_of!(ksu_get_info_legacy_cmd, flags) - 4usize];
    ["Offset of field: ksu_get_info_legacy_cmd::features"]
        [::std::mem::offset_of!(ksu_get_info_legacy_cmd, features) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_report_event_cmd {
    pub event: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_report_event_cmd"][::std::mem::size_of::<ksu_report_event_cmd>() - 4usize];
    ["Alignment of ksu_report_event_cmd"][::std::mem::align_of::<ksu_report_event_cmd>() - 4usize];
    ["Offset of field: ksu_report_event_cmd::event"]
        [::std::mem::offset_of!(ksu_report_event_cmd, event) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_set_sepolicy_cmd {
    pub data_len: __u64,
    pub data: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_set_sepolicy_cmd"][::std::mem::size_of::<ksu_set_sepolicy_cmd>() - 16usize];
    ["Alignment of ksu_set_sepolicy_cmd"][::std::mem::align_of::<ksu_set_sepolicy_cmd>() - 8usize];
    ["Offset of field: ksu_set_sepolicy_cmd::data_len"]
        [::std::mem::offset_of!(ksu_set_sepolicy_cmd, data_len) - 0usize];
    ["Offset of field: ksu_set_sepolicy_cmd::data"]
        [::std::mem::offset_of!(ksu_set_sepolicy_cmd, data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_sepolicy_cmd_hdr {
    pub cmd: __u32,
    pub subcmd: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_sepolicy_cmd_hdr"][::std::mem::size_of::<ksu_sepolicy_cmd_hdr>() - 8usize];
    ["Alignment of ksu_sepolicy_cmd_hdr"][::std::mem::align_of::<ksu_sepolicy_cmd_hdr>() - 4usize];
    ["Offset of field: ksu_sepolicy_cmd_hdr::cmd"]
        [::std::mem::offset_of!(ksu_sepolicy_cmd_hdr, cmd) - 0usize];
    ["Offset of field: ksu_sepolicy_cmd_hdr::subcmd"]
        [::std::mem::offset_of!(ksu_sepolicy_cmd_hdr, subcmd) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_check_safemode_cmd {
    pub in_safe_mode: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_check_safemode_cmd"][::std::mem::size_of::<ksu_check_safemode_cmd>() - 1usize];
    ["Alignment of ksu_check_safemode_cmd"]
        [::std::mem::align_of::<ksu_check_safemode_cmd>() - 1usize];
    ["Offset of field: ksu_check_safemode_cmd::in_safe_mode"]
        [::std::mem::offset_of!(ksu_check_safemode_cmd, in_safe_mode) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_allow_list_cmd {
    pub uids: [__u32; 128usize],
    pub count: __u32,
    pub allow: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_allow_list_cmd"][::std::mem::size_of::<ksu_get_allow_list_cmd>() - 520usize];
    ["Alignment of ksu_get_allow_list_cmd"]
        [::std::mem::align_of::<ksu_get_allow_list_cmd>() - 4usize];
    ["Offset of field: ksu_get_allow_list_cmd::uids"]
        [::std::mem::offset_of!(ksu_get_allow_list_cmd, uids) - 0usize];
    ["Offset of field: ksu_get_allow_list_cmd::count"]
        [::std::mem::offset_of!(ksu_get_allow_list_cmd, count) - 512usize];
    ["Offset of field: ksu_get_allow_list_cmd::allow"]
        [::std::mem::offset_of!(ksu_get_allow_list_cmd, allow) - 516usize];
};
#[repr(C)]
#[derive(Debug)]
pub struct ksu_new_get_allow_list_cmd {
    pub count: __u16,
    pub total_count: __u16,
    pub uids: __IncompleteArrayField<__u32>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_new_get_allow_list_cmd"]
        [::std::mem::size_of::<ksu_new_get_allow_list_cmd>() - 4usize];
    ["Alignment of ksu_new_get_allow_list_cmd"]
        [::std::mem::align_of::<ksu_new_get_allow_list_cmd>() - 4usize];
    ["Offset of field: ksu_new_get_allow_list_cmd::count"]
        [::std::mem::offset_of!(ksu_new_get_allow_list_cmd, count) - 0usize];
    ["Offset of field: ksu_new_get_allow_list_cmd::total_count"]
        [::std::mem::offset_of!(ksu_new_get_allow_list_cmd, total_count) - 2usize];
    ["Offset of field: ksu_new_get_allow_list_cmd::uids"]
        [::std::mem::offset_of!(ksu_new_get_allow_list_cmd, uids) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_uid_granted_root_cmd {
    pub uid: __u32,
    pub granted: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_uid_granted_root_cmd"]
        [::std::mem::size_of::<ksu_uid_granted_root_cmd>() - 8usize];
    ["Alignment of ksu_uid_granted_root_cmd"]
        [::std::mem::align_of::<ksu_uid_granted_root_cmd>() - 4usize];
    ["Offset of field: ksu_uid_granted_root_cmd::uid"]
        [::std::mem::offset_of!(ksu_uid_granted_root_cmd, uid) - 0usize];
    ["Offset of field: ksu_uid_granted_root_cmd::granted"]
        [::std::mem::offset_of!(ksu_uid_granted_root_cmd, granted) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_uid_should_umount_cmd {
    pub uid: __u32,
    pub should_umount: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_uid_should_umount_cmd"]
        [::std::mem::size_of::<ksu_uid_should_umount_cmd>() - 8usize];
    ["Alignment of ksu_uid_should_umount_cmd"]
        [::std::mem::align_of::<ksu_uid_should_umount_cmd>() - 4usize];
    ["Offset of field: ksu_uid_should_umount_cmd::uid"]
        [::std::mem::offset_of!(ksu_uid_should_umount_cmd, uid) - 0usize];
    ["Offset of field: ksu_uid_should_umount_cmd::should_umount"]
        [::std::mem::offset_of!(ksu_uid_should_umount_cmd, should_umount) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_manager_appid_cmd {
    pub appid: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_manager_appid_cmd"]
        [::std::mem::size_of::<ksu_get_manager_appid_cmd>() - 4usize];
    ["Alignment of ksu_get_manager_appid_cmd"]
        [::std::mem::align_of::<ksu_get_manager_appid_cmd>() - 4usize];
    ["Offset of field: ksu_get_manager_appid_cmd::appid"]
        [::std::mem::offset_of!(ksu_get_manager_appid_cmd, appid) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ksu_get_app_profile_cmd {
    pub profile: app_profile,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_app_profile_cmd"]
        [::std::mem::size_of::<ksu_get_app_profile_cmd>() - 784usize];
    ["Alignment of ksu_get_app_profile_cmd"]
        [::std::mem::align_of::<ksu_get_app_profile_cmd>() - 8usize];
    ["Offset of field: ksu_get_app_profile_cmd::profile"]
        [::std::mem::offset_of!(ksu_get_app_profile_cmd, profile) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ksu_set_app_profile_cmd {
    pub profile: app_profile,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_set_app_profile_cmd"]
        [::std::mem::size_of::<ksu_set_app_profile_cmd>() - 784usize];
    ["Alignment of ksu_set_app_profile_cmd"]
        [::std::mem::align_of::<ksu_set_app_profile_cmd>() - 8usize];
    ["Offset of field: ksu_set_app_profile_cmd::profile"]
        [::std::mem::offset_of!(ksu_set_app_profile_cmd, profile) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_feature_cmd {
    pub feature_id: __u32,
    pub value: __u64,
    pub supported: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_feature_cmd"][::std::mem::size_of::<ksu_get_feature_cmd>() - 24usize];
    ["Alignment of ksu_get_feature_cmd"][::std::mem::align_of::<ksu_get_feature_cmd>() - 8usize];
    ["Offset of field: ksu_get_feature_cmd::feature_id"]
        [::std::mem::offset_of!(ksu_get_feature_cmd, feature_id) - 0usize];
    ["Offset of field: ksu_get_feature_cmd::value"]
        [::std::mem::offset_of!(ksu_get_feature_cmd, value) - 8usize];
    ["Offset of field: ksu_get_feature_cmd::supported"]
        [::std::mem::offset_of!(ksu_get_feature_cmd, supported) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_set_feature_cmd {
    pub feature_id: __u32,
    pub value: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_set_feature_cmd"][::std::mem::size_of::<ksu_set_feature_cmd>() - 16usize];
    ["Alignment of ksu_set_feature_cmd"][::std::mem::align_of::<ksu_set_feature_cmd>() - 8usize];
    ["Offset of field: ksu_set_feature_cmd::feature_id"]
        [::std::mem::offset_of!(ksu_set_feature_cmd, feature_id) - 0usize];
    ["Offset of field: ksu_set_feature_cmd::value"]
        [::std::mem::offset_of!(ksu_set_feature_cmd, value) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_wrapper_fd_cmd {
    pub fd: __u32,
    pub flags: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_wrapper_fd_cmd"][::std::mem::size_of::<ksu_get_wrapper_fd_cmd>() - 8usize];
    ["Alignment of ksu_get_wrapper_fd_cmd"]
        [::std::mem::align_of::<ksu_get_wrapper_fd_cmd>() - 4usize];
    ["Offset of field: ksu_get_wrapper_fd_cmd::fd"]
        [::std::mem::offset_of!(ksu_get_wrapper_fd_cmd, fd) - 0usize];
    ["Offset of field: ksu_get_wrapper_fd_cmd::flags"]
        [::std::mem::offset_of!(ksu_get_wrapper_fd_cmd, flags) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_manage_mark_cmd {
    pub operation: __u32,
    pub pid: __s32,
    pub result: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_manage_mark_cmd"][::std::mem::size_of::<ksu_manage_mark_cmd>() - 12usize];
    ["Alignment of ksu_manage_mark_cmd"][::std::mem::align_of::<ksu_manage_mark_cmd>() - 4usize];
    ["Offset of field: ksu_manage_mark_cmd::operation"]
        [::std::mem::offset_of!(ksu_manage_mark_cmd, operation) - 0usize];
    ["Offset of field: ksu_manage_mark_cmd::pid"]
        [::std::mem::offset_of!(ksu_manage_mark_cmd, pid) - 4usize];
    ["Offset of field: ksu_manage_mark_cmd::result"]
        [::std::mem::offset_of!(ksu_manage_mark_cmd, result) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_hook_mode_cmd {
    pub mode: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_hook_mode_cmd"][::std::mem::size_of::<ksu_get_hook_mode_cmd>() - 16usize];
    ["Alignment of ksu_get_hook_mode_cmd"]
        [::std::mem::align_of::<ksu_get_hook_mode_cmd>() - 1usize];
    ["Offset of field: ksu_get_hook_mode_cmd::mode"]
        [::std::mem::offset_of!(ksu_get_hook_mode_cmd, mode) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_version_tag_cmd {
    pub tag: [::std::os::raw::c_char; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_version_tag_cmd"][::std::mem::size_of::<ksu_get_version_tag_cmd>() - 32usize];
    ["Alignment of ksu_get_version_tag_cmd"]
        [::std::mem::align_of::<ksu_get_version_tag_cmd>() - 1usize];
    ["Offset of field: ksu_get_version_tag_cmd::tag"]
        [::std::mem::offset_of!(ksu_get_version_tag_cmd, tag) - 0usize];
};
pub const KSU_MARK_GET: __u32 = 1;
pub const KSU_MARK_MARK: __u32 = 2;
pub const KSU_MARK_UNMARK: __u32 = 3;
pub const KSU_MARK_REFRESH: __u32 = 4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_nuke_ext4_sysfs_cmd {
    pub arg: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_nuke_ext4_sysfs_cmd"][::std::mem::size_of::<ksu_nuke_ext4_sysfs_cmd>() - 8usize];
    ["Alignment of ksu_nuke_ext4_sysfs_cmd"]
        [::std::mem::align_of::<ksu_nuke_ext4_sysfs_cmd>() - 8usize];
    ["Offset of field: ksu_nuke_ext4_sysfs_cmd::arg"]
        [::std::mem::offset_of!(ksu_nuke_ext4_sysfs_cmd, arg) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_add_try_umount_cmd {
    pub arg: __u64,
    pub flags: __u32,
    pub mode: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_add_try_umount_cmd"][::std::mem::size_of::<ksu_add_try_umount_cmd>() - 16usize];
    ["Alignment of ksu_add_try_umount_cmd"]
        [::std::mem::align_of::<ksu_add_try_umount_cmd>() - 8usize];
    ["Offset of field: ksu_add_try_umount_cmd::arg"]
        [::std::mem::offset_of!(ksu_add_try_umount_cmd, arg) - 0usize];
    ["Offset of field: ksu_add_try_umount_cmd::flags"]
        [::std::mem::offset_of!(ksu_add_try_umount_cmd, flags) - 8usize];
    ["Offset of field: ksu_add_try_umount_cmd::mode"]
        [::std::mem::offset_of!(ksu_add_try_umount_cmd, mode) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_sulog_fd_cmd {
    pub flags: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_sulog_fd_cmd"][::std::mem::size_of::<ksu_get_sulog_fd_cmd>() - 4usize];
    ["Alignment of ksu_get_sulog_fd_cmd"][::std::mem::align_of::<ksu_get_sulog_fd_cmd>() - 4usize];
    ["Offset of field: ksu_get_sulog_fd_cmd::flags"]
        [::std::mem::offset_of!(ksu_get_sulog_fd_cmd, flags) - 0usize];
};
pub const KSU_UMOUNT_WIPE: __u8 = 0;
pub const KSU_UMOUNT_ADD: __u8 = 1;
pub const KSU_UMOUNT_DEL: __u8 = 2;
pub const KSU_IOCTL_GRANT_ROOT: __u32 = 19201;
pub const KSU_IOCTL_GET_INFO: __u32 = 2148551426;
pub const KSU_IOCTL_GET_INFO_LEGACY: __u32 = 2147502850;
pub const KSU_IOCTL_REPORT_EVENT: __u32 = 1073761027;
pub const KSU_IOCTL_SET_SEPOLICY: __u32 = 3221244676;
pub const KSU_IOCTL_CHECK_SAFEMODE: __u32 = 2147502853;
pub const KSU_IOCTL_GET_ALLOW_LIST: __u32 = 3221244678;
pub const KSU_IOCTL_GET_DENY_LIST: __u32 = 3221244679;
pub const KSU_IOCTL_NEW_GET_ALLOW_LIST: __u32 = 3221506822;
pub const KSU_IOCTL_NEW_GET_DENY_LIST: __u32 = 3221506823;
pub const KSU_IOCTL_UID_GRANTED_ROOT: __u32 = 3221244680;
pub const KSU_IOCTL_UID_SHOULD_UMOUNT: __u32 = 3221244681;
pub const KSU_IOCTL_GET_MANAGER_APPID: __u32 = 2147502858;
pub const KSU_IOCTL_GET_APP_PROFILE: __u32 = 3221244683;
pub const KSU_IOCTL_SET_APP_PROFILE: __u32 = 1073761036;
pub const KSU_IOCTL_GET_FEATURE: __u32 = 3221244685;
pub const KSU_IOCTL_SET_FEATURE: __u32 = 1073761038;
pub const KSU_IOCTL_GET_WRAPPER_FD: __u32 = 1073761039;
pub const KSU_IOCTL_MANAGE_MARK: __u32 = 3221244688;
pub const KSU_IOCTL_NUKE_EXT4_SYSFS: __u32 = 1073761041;
pub const KSU_IOCTL_ADD_TRY_UMOUNT: __u32 = 1073761042;
pub const KSU_IOCTL_SET_INIT_PGRP: __u32 = 19219;
pub const KSU_IOCTL_GET_SULOG_FD: __u32 = 1074023188;
pub const KSU_IOCTL_DISABLE_ESCAPE_TO_ROOT: __u32 = 19221;
pub const KSU_IOCTL_GET_HOOK_MODE: __u32 = 2147502946;
pub const KSU_IOCTL_GET_VERSION_TAG: __u32 = 2147502947;
pub const KSU_IOCTL_GET_FULL_VERSION: __u32 = 2147502948;
pub const KSU_IOCTL_HOOK_TYPE: __u32 = 2147502949;
pub const KSU_IOCTL_ENABLE_KPM: __u32 = 2147502950;
pub const KSU_IOCTL_KPM: __u32 = 3221244872;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_get_full_version_cmd {
    pub version_full: [::std::os::raw::c_char; 255usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_get_full_version_cmd"]
        [::std::mem::size_of::<ksu_get_full_version_cmd>() - 255usize];
    ["Alignment of ksu_get_full_version_cmd"]
        [::std::mem::align_of::<ksu_get_full_version_cmd>() - 1usize];
    ["Offset of field: ksu_get_full_version_cmd::version_full"]
        [::std::mem::offset_of!(ksu_get_full_version_cmd, version_full) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_hook_type_cmd {
    pub hook_type: [::std::os::raw::c_char; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_hook_type_cmd"][::std::mem::size_of::<ksu_hook_type_cmd>() - 32usize];
    ["Alignment of ksu_hook_type_cmd"][::std::mem::align_of::<ksu_hook_type_cmd>() - 1usize];
    ["Offset of field: ksu_hook_type_cmd::hook_type"]
        [::std::mem::offset_of!(ksu_hook_type_cmd, hook_type) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_enable_kpm_cmd {
    pub enabled: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_enable_kpm_cmd"][::std::mem::size_of::<ksu_enable_kpm_cmd>() - 1usize];
    ["Alignment of ksu_enable_kpm_cmd"][::std::mem::align_of::<ksu_enable_kpm_cmd>() - 1usize];
    ["Offset of field: ksu_enable_kpm_cmd::enabled"]
        [::std::mem::offset_of!(ksu_enable_kpm_cmd, enabled) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_kpm_cmd {
    pub control_code: __u64,
    pub arg1: __u64,
    pub arg2: __u64,
    pub result_code: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_kpm_cmd"][::std::mem::size_of::<ksu_kpm_cmd>() - 32usize];
    ["Alignment of ksu_kpm_cmd"][::std::mem::align_of::<ksu_kpm_cmd>() - 8usize];
    ["Offset of field: ksu_kpm_cmd::control_code"]
        [::std::mem::offset_of!(ksu_kpm_cmd, control_code) - 0usize];
    ["Offset of field: ksu_kpm_cmd::arg1"][::std::mem::offset_of!(ksu_kpm_cmd, arg1) - 8usize];
    ["Offset of field: ksu_kpm_cmd::arg2"][::std::mem::offset_of!(ksu_kpm_cmd, arg2) - 16usize];
    ["Offset of field: ksu_kpm_cmd::result_code"]
        [::std::mem::offset_of!(ksu_kpm_cmd, result_code) - 24usize];
};
pub const SUKISU_KPM_LOAD: __u32 = 1;
pub const SUKISU_KPM_UNLOAD: __u32 = 2;
pub const SUKISU_KPM_NUM: __u32 = 3;
pub const SUKISU_KPM_LIST: __u32 = 4;
pub const SUKISU_KPM_INFO: __u32 = 5;
pub const SUKISU_KPM_CONTROL: __u32 = 6;
pub const SUKISU_KPM_VERSION: __u32 = 7;
pub const ksu_feature_id_KSU_FEATURE_SU_COMPAT: ksu_feature_id = 0;
pub const ksu_feature_id_KSU_FEATURE_KERNEL_UMOUNT: ksu_feature_id = 1;
pub const ksu_feature_id_KSU_FEATURE_SULOG: ksu_feature_id = 2;
pub const ksu_feature_id_KSU_FEATURE_ADB_ROOT: ksu_feature_id = 3;
pub const ksu_feature_id_KSU_FEATURE_SELINUX_HIDE: ksu_feature_id = 4;
pub const ksu_feature_id_KSU_FEATURE_SET_SELINUX_ENFORCE: ksu_feature_id = 5;
pub const ksu_feature_id_KSU_FEATURE_AVC_SPOOF: ksu_feature_id = 10003;
pub const ksu_feature_id_KSU_FEATURE_MAX: ksu_feature_id = 10004;
pub type ksu_feature_id = ::std::os::raw::c_uint;
pub const KSU_SEPOLICY_CMD_NORMAL_PERM: __u32 = 1;
pub const KSU_SEPOLICY_CMD_XPERM: __u32 = 2;
pub const KSU_SEPOLICY_CMD_TYPE_STATE: __u32 = 3;
pub const KSU_SEPOLICY_CMD_TYPE: __u32 = 4;
pub const KSU_SEPOLICY_CMD_TYPE_ATTR: __u32 = 5;
pub const KSU_SEPOLICY_CMD_ATTR: __u32 = 6;
pub const KSU_SEPOLICY_CMD_TYPE_TRANSITION: __u32 = 7;
pub const KSU_SEPOLICY_CMD_TYPE_CHANGE: __u32 = 8;
pub const KSU_SEPOLICY_CMD_GENFSCON: __u32 = 9;
pub const KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW: __u32 = 1;
pub const KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY: __u32 = 2;
pub const KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW: __u32 = 3;
pub const KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT: __u32 = 4;
pub const KSU_SEPOLICY_SUBCMD_XPERM_ALLOW: __u32 = 1;
pub const KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW: __u32 = 2;
pub const KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT: __u32 = 3;
pub const KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE: __u32 = 1;
pub const KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE: __u32 = 2;
pub const KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE: __u32 = 1;
pub const KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER: __u32 = 2;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clone_args {
    pub flags: __u64,
    pub pidfd: __u64,
    pub child_tid: __u64,
    pub parent_tid: __u64,
    pub exit_signal: __u64,
    pub stack: __u64,
    pub stack_size: __u64,
    pub tls: __u64,
    pub set_tid: __u64,
    pub set_tid_size: __u64,
    pub cgroup: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of clone_args"][::std::mem::size_of::<clone_args>() - 88usize];
    ["Alignment of clone_args"][::std::mem::align_of::<clone_args>() - 8usize];
    ["Offset of field: clone_args::flags"][::std::mem::offset_of!(clone_args, flags) - 0usize];
    ["Offset of field: clone_args::pidfd"][::std::mem::offset_of!(clone_args, pidfd) - 8usize];
    ["Offset of field: clone_args::child_tid"]
        [::std::mem::offset_of!(clone_args, child_tid) - 16usize];
    ["Offset of field: clone_args::parent_tid"]
        [::std::mem::offset_of!(clone_args, parent_tid) - 24usize];
    ["Offset of field: clone_args::exit_signal"]
        [::std::mem::offset_of!(clone_args, exit_signal) - 32usize];
    ["Offset of field: clone_args::stack"][::std::mem::offset_of!(clone_args, stack) - 40usize];
    ["Offset of field: clone_args::stack_size"]
        [::std::mem::offset_of!(clone_args, stack_size) - 48usize];
    ["Offset of field: clone_args::tls"][::std::mem::offset_of!(clone_args, tls) - 56usize];
    ["Offset of field: clone_args::set_tid"][::std::mem::offset_of!(clone_args, set_tid) - 64usize];
    ["Offset of field: clone_args::set_tid_size"]
        [::std::mem::offset_of!(clone_args, set_tid_size) - 72usize];
    ["Offset of field: clone_args::cgroup"][::std::mem::offset_of!(clone_args, cgroup) - 80usize];
};
pub const ksu_sulog_event_type_KSU_SULOG_EVENT_ROOT_EXECVE: ksu_sulog_event_type = 1;
pub const ksu_sulog_event_type_KSU_SULOG_EVENT_SUCOMPAT: ksu_sulog_event_type = 2;
pub const ksu_sulog_event_type_KSU_SULOG_EVENT_IOCTL_GRANT_ROOT: ksu_sulog_event_type = 3;
pub type ksu_sulog_event_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ksu_sulog_event {
    pub version: __u16,
    pub event_type: __u16,
    pub retval: __s32,
    pub pid: __u32,
    pub tgid: __u32,
    pub ppid: __u32,
    pub uid: __u32,
    pub euid: __u32,
    pub comm: [::std::os::raw::c_char; 16usize],
    pub filename_len: __u32,
    pub argv_len: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ksu_sulog_event"][::std::mem::size_of::<ksu_sulog_event>() - 52usize];
    ["Alignment of ksu_sulog_event"][::std::mem::align_of::<ksu_sulog_event>() - 4usize];
    ["Offset of field: ksu_sulog_event::version"]
        [::std::mem::offset_of!(ksu_sulog_event, version) - 0usize];
    ["Offset of field: ksu_sulog_event::event_type"]
        [::std::mem::offset_of!(ksu_sulog_event, event_type) - 2usize];
    ["Offset of field: ksu_sulog_event::retval"]
        [::std::mem::offset_of!(ksu_sulog_event, retval) - 4usize];
    ["Offset of field: ksu_sulog_event::pid"]
        [::std::mem::offset_of!(ksu_sulog_event, pid) - 8usize];
    ["Offset of field: ksu_sulog_event::tgid"]
        [::std::mem::offset_of!(ksu_sulog_event, tgid) - 12usize];
    ["Offset of field: ksu_sulog_event::ppid"]
        [::std::mem::offset_of!(ksu_sulog_event, ppid) - 16usize];
    ["Offset of field: ksu_sulog_event::uid"]
        [::std::mem::offset_of!(ksu_sulog_event, uid) - 20usize];
    ["Offset of field: ksu_sulog_event::euid"]
        [::std::mem::offset_of!(ksu_sulog_event, euid) - 24usize];
    ["Offset of field: ksu_sulog_event::comm"]
        [::std::mem::offset_of!(ksu_sulog_event, comm) - 28usize];
    ["Offset of field: ksu_sulog_event::filename_len"]
        [::std::mem::offset_of!(ksu_sulog_event, filename_len) - 44usize];
    ["Offset of field: ksu_sulog_event::argv_len"]
        [::std::mem::offset_of!(ksu_sulog_event, argv_len) - 48usize];
};
unsafe extern "C" {
    pub static mut __packed: ksu_sulog_event;
}
